#!/usr/bin/perl

use Gimp ":auto";
use Gimp::Fu;

sub text1 {
    my($font, $text) = @_;
    
    # Create a new image
    $img = gimp_image_new(350, 100, RGB);

    # Create a new layer and draw it to the image at the top
    $drw = gimp_layer_new($img, $img->width, $img->height,
			  RGB, "BG", 100, NORMAL_MODE);
    $drw->add_layer(-1);
    gimp_palette_set_background("black");
    gimp_edit_fill($drw, BACKGROUND_FILL);


    # Choose color of text
    gimp_palette_set_foreground([255,255,0]);

    # Create the text
    my $border = 10;
    my ($size) = ($font=~ /(\d+)/);  # Extract size from font name
    my $text_layer = gimp_text_fontname($drw,  0, 0, $text,
					$border, 1, 
					$size, POINTS, $font);
    gimp_floating_sel_anchor($text_layer);
    
    return $img;
}

# register the script
register "hello_world1", "basic text", "basic text", "Dov", "Dov",
    "2004-03-27",
    "<Toolbox>/Xtns/Perl-Fu/Tutorial/Basic text 1", 
    "*",
    [
     [PF_FONT, "font", "font", "Sans 70"],
     [PF_STRING, "text", "text", "Hello world!"]
    ],
    \&text1;

# Handle over control to gimp
exit main();
