<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
  <HEAD>
    <TITLE>Using Perl::Gimp through CGI (19-Jul-1998)</TITLE>
    <!-- Created by: Dov Grobgeld, 19-Jul-1998 -->
    <!-- Changed by: Dov Grobgeld, 19-Jul-1998 -->


  </HEAD>
  <BODY>
    <H1>Using Perl::Gimp through CGI</H1>
    The following text describes a way of using Perl::Gimp together
    with CGI-bin.

    <H2>perl scripts</H2>
    Create perl-scripts that can be run from the command line.

    <H2>cgi-script</H2>
    Create a cgi-bin script that should take the parameters from
    HTML form and executes the command line perl script with
    those parameters. Be extremely careful with shell escapes
    when doing this, as we are passing parameters received from
    the user and passing these on to the shell. 

    <h2>Starting gimp</h2>
    Start gimp with a shell script containing the following commands:
    <pre>
      xhost +localhost
      gimp --no-interface --batch "(extension_perl_server 0 0 0)"
      chmod -R og+w /tmp/gimp-perl-serv
    </pre>
    The last comman enables anybody on the local server to connect
    to the gimp-process. If this is not desired, then gimp and
    the httpd must be running under the same UID, or at least under
    the same GID.


  </BODY>
</HTML>