<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
<head>
<title>A Tutorial for Perl Gimp Users</title>
    <link rel="stylesheet" href="dov-colors.css" type="text/css" />
</head>
<:

BEGIN {
    $sec=0;
    $subsec=0;
    open(TOC, "perl-toc.html");
    $toc = join("", <TOC>);
    open(TOC, ">perl-toc.html");
    print TOC "<ul>\n";
}

END {
    print TOC "</ul>\n";
    close(TOC);
}

sub html_quote {
    my $html = shift;
    $html=~ s/&/&amp;/g;
    $html=~ s/</&lt;/g;
    $html=~ s/>/&gt;/g;
    return $html;
}

sub warning {
    my $text = shift;
    print
        "<center>\n"
       ."  <table border width=75%>\n"
       ."    <tr><td bgcolor=#ffffcc><font color=#800040><h2 align=center>Note!</h3></font><font color=#800000 size=+1>$text</font>"
       ."  </table>\n"
       ."</center>\n";
}

sub section {
   $sec++;
   $subsec=0;
   print "<h2><a name=\"SEC$sec\">$sec. @_</a></h2>\n";
   print TOC "<li> <a href=\"#SEC$sec\">$sec. @_</a></li>\n";
}

sub subsection {
   $subsec++;
   print "<h3><a name=\"SEC$sec.$subsec\">$sec.$subsec. @_</a></h3>\n";
   print TOC "<li> <a href=\"#SEC$sec.$subsec\">$sec.$subsec. @_</a></li>\n";
}

sub mycomment {
   print "<i><font color=\"#8B5A00\">@_</font></i><p>";
}

sub dtb { print "<dt><b>@_</b>" }

sub pdb {
    my($name, $blurb, $in, $out, $help) = @_;
    my $nin = @$in;
    my $nout = @$out;
    my $tablecolor = "#e0e0e0";
    my $th = "th valign=top";
    my $td = "td valign=top";

    print "<p><table><tr><td bgcolor=$tablecolor>\n";
    print "<table>\n";
    print "<tr><$th align=right>Name:</th><td bgcolor=#e0e0ff colspan=3>$name</td></tr>\n";
    print "<tr><$th align=right>Blurb:</th><$td colspan=3>$blurb</td></tr>\n";
    my $first=1;
    foreach $i (0..$nin-1) {
       print "<tr>\n";
       if ($i == 0) {
           print "<$th align=right valign=top>In:</th>";
       }
       else {
           print "<$th></th>";
       }
       print "<$td>$in->[$i][1]</td><$td>$in->[$i][0]</td><$td>$in->[$i][2]</td>\n";
       print "</tr>\n";
    }
    foreach $i (0..$nout-1) {
       print "<tr><$th align=right>Out:</th></tr>" if $i==0;
       print "<tr><td></td>";
       print "<$td>$out->[$i][1]</td><$td>$out->[$i][0]</td><$td>$out->[$i][2]</td>\n";
       print "</tr>\n";
    }
    if ($help) {
        print "<tr><$th valign=top>Help:</th><td colspan=3>$help</td></tr>";
    }
    print "</table>\n";
    print "</table></p>\n";
}

sub code_snippet {   # usage: code_snippet($filename, title)
   my $filename = shift;
   my $title = shift || "$filename";
   my $snippet = shift;
   my $lineno = 0;
   my $par;
   $par = "<table border>" .
           "<tr><th bgcolor=#E0E0FF><a href=\"$filename\">$title</a>" .
	   "<tr><td bgcolor=#FFE0E0><pre>";
   open(IN, $filename);
   while(<IN>) {
       chomp;
       $_ = html_quote($_);
       $lineno++;
       my $pref = "     ";
       $pref = sprintf("%3d: ", $lineno);
       $par.= "<font size=-1 color=red>$pref </font>$_ \n";
   }
   close(IN);
   chop($par);
   $par.= "</pre></table><br>";
   print $par;
}
$tpix="<img src=\"tpix.gif\" width=0>";
:>

<body>
<div class="box">
<h1 align=center>A Tutorial for Gimp-Perl Users<br>
  		Updated for Gimp 2.8 / Gimp-Perl 2.3<br>
    <font size=-1>&#169; Ed J</font><br>
    <font size=-1>Last modified: 2014-05-01</font><br>
</h1>

<h2>Table of contents</h2>
<: print $toc :>

<: section("Version notes") :>
This work is a slightly modified version of Dov Grobgeld's excellent
tutorial. It has been updated to Gimp-Perl 2.3.
<p>

<: section("Background") :>
One of the wonderful features of GIMP is that it all its functionality may
be accessed through scripting. Available scripting environments include
Scheme through Script-Fu, and Python. Scheme can be a little difficult
to use if one does not already know the language.
<p>
Perl as a language is probably more familiar to web-literate users,
as it is the major language for writing CGI scripts. Now, 
GIMP scripts may also be written with Perl. This tutorial will describe
how to write such plug-ins and scripts for Gimp.<p>

As there are several excellent tutorial texts describing the perl
language, this tutorial will assume a working knowledge of Perl,
and will instead concentrate on the use of GIMP together with the
perl modules Gimp and Gimp::Fu.

<: section("What you need") :>

  The tutorial scripts have been tested on Linux (a Windows version is
  in the works) with the following versions:
  <OL>
    <LI> Gimp version 2.8.10. </LI>
    
    <LI> Perl version 5.14 or later. </LI>
    
    <LI> The perl module Gtk2, version 1.249, available from <a href="http://gtk2-perl.sourceforge.net/">http://gtk2-perl.sourceforge.net</a> </LI>
    
    <LI> The Gimp module, version 2.0pre1 or later, available from
    <a href="http://search.cpan.org/dist/Gimp/">http://search.cpan.org/dist/Gimp/</a></LI>
  </OL>
  Perl and all its associated modules are available in source form from
  the Comprehensive Perl Archive network, CPAN.

<: section("The Gimp module") :>
Most scripts make use of the simplified interface Gimp::Fu provided
with the Gimp module. Gimp::Fu provides a framework for entering
parameters to the script in a dialog-box interface, just like Script-Fu,
but also allows running of the script in batch mode from the command line.
This tutorial will go into detailed descriptions of the construction of
a Gimp::Fu script, but before we do this, here is the general framework
of such a script.<p>

<: code_snippet("basic") :>

The key points to note in the script are:
<ul>
<li>the use of the two
modules <tt>Gimp</tt> and <tt>Gimp::Fu</tt>,
<li>the podregister function, which will be described in detail below,
<li>the way the control is
handed over to <tt>Gimp</tt> module on line 8, and
<li>the POD documentation below the <tt>__END__</tt> line.
</ul>

<: section("The GIMP PDB") :>
Before going into the details of the Gimp::Fu script, we will
describe how to access the functionality of GIMP.  All
functions known to GIMP are available through the procedural database
(PDB). All the PDB functions may be called from perl, as will be seen
below. These PDB functions are either internal to GIMP, or have been
made available through a plug-in or a script extension, but as far as
the caller is concerned there is no difference. As we will see below,
when a perl function is registered through the <tt>podregister</tt>
function, it will appear in the PDB as well.

<p>Gimp comes with a PDB browser available
in <b>Help/Procedure Browser</b>. This browser provides a way of seeing
all the functions in the PDB, as well as their input and output
parameters. E.g. the DB Browser entry for
<tt>gimp-image-new</tt>, which will be used in the example below
looks like this:
<p>
<: pdb("plug-in-gauss-iir",
       "Apply a gaussian blur",
       [ ["run-mode", "INT32", "The run mode { RUN-INTERACTIVE (0), RUN-NONINTERACTIVE (1) }"],
	 ["image", "IMAGE", "Input image (unused)"],
	 ["drawable", "DRAWABLE", "Input drawable"],
         ["radius", "FLOAT", "Radius of gaussian blur (in pixels, > 0.0)"],
         ["horizontal", "INT32", "Blur in horizontal direction"],
         ["vertical", "INT32", "Blur in vertical direction"],
	 ],
	 [ ],
	 "Applies a gaussian blur to the drawable, with specified radius of affect.  The standard deviation of the normal distribution used to modify pixel values is calculated based on the supplied radius.  Horizontal and vertical blurring can be independently invoked by specifying only one to run.  The IIR gaussian blurring works best for large radius values and for images which are not computer-generated."
	 ) :>

All the the constants mentioned in the PDB Explorer have been defined
within Gimp::Fu and may be used within perl. E.g. a call to
blur an image looks as follows:

<pre>
   Gimp::Plugin-&gt;gauss_iir($image, $drawable, 50, 6, 6);</pre>

Note that Perl is using underline characters where the DB browser
uses hyphens! The PDB entry above shows that <tt>plug-in-gauss-iir</tt>
is called with various parameters, of various types. These will be
explained below.

<p> You will also see that the first parameter, <tt>run-mode</tt>,
was omitted. This is a feature of Gimp-Perl, which will automatically
supply that parameter if you leave it off. This will make your code a
lot tidier-looking.

<p>
Script-Fu scripts are called just like any other script according
to the PDB signature in the PDB browser. E.g. to run the
script-fu-basic1-logo just do:
<pre>
script_fu_basic1_logo("Hello", 72,
                      "Utopia 72", 
                      [0,0,0],[255,255,255]);</pre>

<: subsection("Gimp::Fu and the podregister function") :>
  Gimp::Fu is Perl's answer to Script-Fu. It provides a simplified method
  for accepting parameters for a script through a Gtk2 interface,
  just like script-fu, but as we shall see below, it has some additional
  bells and whistles.<p>

  The main function for a Gimp-Fu script is the <tt>podregister</tt> function.
  This function declares the interface of the script to GIMP. The
  <tt>podregister</tt> function provides GIMP with the following information,
  from various sections of its
  <a href="http://perldoc.perl.org/perlpod.html">POD (plain old
  documentation)</a>:
  <OL>
    <LI> The name of the function. It comes from the first part of the
      <tt>NAME</tt> section, before the dash. Tells GIMP the name by which
      the function will be known in the PDB. </LI><P>
    <LI> A small description, from the <tt>NAME</tt> section, after the
      dash. </LI><p>
    <LI> A help text, from the <tt>DESCRIPTION</tt> section. </LI><p>
    <LI> The author's name, from the <tt>AUTHOR</tt> section. </LI><p>
    <LI> The copyright of the script, from the <tt>LICENSE</tt> section. </LI><p>
    <LI> Creation date - any text, from the <tt>DATE</tt> section. </LI><p>
    <LI> Menu path - a string, from the <tt>SYNOPSIS</tt> section.
      The path can take these forms, though there are other options:
      <OL>
	<LI> "&lt;Toolbox&gt;/Xtns/Perl/Script Name" </LI>
	<LI> "&lt;Image&gt;/Perl-Fu/Script Name" </LI>
      </OL>
      If form 1. is given, then the script is a standalone script
      that appears in the menu hierarchy under Xtns/Perl-Fu and
      takes all its inputs through the Gimp::Fu interface dialog.
      If form 2. is given on the other hand, then the script
      is tied to the image menu popped up through the right hand
      button over any image. In this case Gimp::Fu will add as
      the first two parameters to the script the image and the
      drawable active when the script was invoked.
    </LI><p>
    <LI> The acceptable image types, from the <tt>IMAGE TYPES</tt>
	 section - a string. This list contains
         a list of image types acceptable. This field is only used
         for scripts that are in the "&lt;Image&gt;" hieararchy.
	 Possible values are listed in the table below:
	     <: $th="<th bgcolor=#dfdfdf>";
		$td="<td bgcolor=#dfdfee valign=top>" :>
	     <table>
	       <tr><:=$th:>value</th><:=$th:>meaning</th></tr>
	       <tr><:=$td:>*<:=$td:>Any images are accepted</tr>
               <tr><:=$td:>RGB <:=$td:>RGB images</tr>
               <tr><:=$td:>RGBA <:=$td:>RGB images with alpha channels</tr>
               <tr><:=$td:>GREY <:=$td:>Grey level images</tr>
	     </table>
    </LI><p>
    <LI> Parameters, from the <tt>PARAMETERS</tt> section. This will be
      Perl code, which Gimp::Fu evaluates as a list of parameters.
      Each parameter in turn is a reference to an array containing the
      following four or five values (A reference to an array in Perl is
      simply an array written within square brackets):
      <OL>
	<LI> The type of the parameter. The types recognized by
	    Gimp::Fu and their Perl counterparts are given in the
	    following table:
	     <: $th="<th bgcolor=#dfdfdf>";
		$td="<td bgcolor=#dfdfee valign=top>";
		sub th { print "<th bgcolor=#dfdfdf @_>" };
	     :>
	     <table>
	       <tr><:=$th:>Type</th><:th "width=30%":>Possible forms</th>
                   <:th "width=50%":>Comment</tr>
	       <tr><:=$td:>PF_INT32<br>
		           PF_INT16<br>
			   PF_INT8<br><:=$td:>42<:=$td:>An integer.</tr>
	       <tr><:=$td:>PF_FLOAT<br><:=$td:>3.141<:=$td:>A floating point number.
               <tr><:=$td:>PF_TOGGLE
		           <:=$td:>0<br>1<:=$td:>A boolean value.
               <tr><:=$td:>PF_SLIDER<br>
		           PF_SPINNER
	           <:=$td:>An integer value through a slider and a spinner interface. The range parameter should be specified and is interpreted as minimum, maximum, and step, e.g. [0,100,1].
		   <:=$td:><:=$tpix:>
               <tr><:=$td:>PF_FONT<:=$td:>"Arial"<:=$td:>A font name.
               <tr><:=$td:>PF_STRING<:=$td:>"A string"<:=$td:>A string</tr>
	       <tr><:=$td:>PF_COLOR<br>
		           PF_COLOUR<:=$td:>[255,127,0]<br>
				          <tt>#ff7f00</tt>
	       <:=$td:>A color may either be expressed as a reference
	              to an array of three components, or as a hexadecimal
	              triple, proceeded by the hash sign.</tr>
	       <tr><:=$td:>PF_TOGGLE<:=$td:>0<br>1<:=$td:>A boolean toggle
	       <tr><:=$td:>PF_IMAGE<:=$td:>-<:=$td:>An image
	       <tr><:=$td:>PF_DRAWABLE<:=$td:>-<:=$td:>A drawable.
	       <tr><:=$td:>PF_BRUSH<:=$td:><:=$tpix:><:=$td:>A brush
	       <tr><:=$td:>PF_GRADIENT<:=$td:><:=$tpix:><:=$td:>A gradient
	       <tr><:=$td:>PF_PATTERN<:=$td:><:=$tpix:><:=$td:>A pattern
	     </table>
	</LI>
	<LI> The name of the parameter - a string. </LI>
	<LI> A help text for the parameter. </LI>
	<LI> Default value for the parameter. This should be given in
	     the form listed in the table above.
 	</LI>
	<LI> An array defining allowed range for the value. This is
	     only used for PF_SLIDER and PF_SPINNER.</LI>
      </ol><P>
      <LI> Optionally, the return types of the function can be provided,
	from a <tt>RETURN VALUES</tt> section. This is specified in the
	same way as the Parameters above. There is no default or extra
	argument required. <p>
      </LI>
      <LI> The perl code implementing the function. This
	will be called when the associated menu entry
	declared through the <i>Menu path</i> described above.
	When the sub is called it is passed a list
	of parameters as declared in field 9. In
	the case of a "&lt;Image&gt;..." script, the active image
	and drawable (layer or channel) as first and second parameters.
	Thanks to the magic of Perl source filtering, you do not need
	to declare your variables but may simply use them:
	<pre>
    podregister {
      $drawable->gauss_iir($radius, $horizontal, $vertical);
    };
    # ...
    =head1 PARAMETERS
    
      [ PF_FLOAT, 'radius', "Radius", 50.0 ],
      [ PF_INT32, 'horizontal', 'Horizontal blur', 6 ],
      [ PF_INT32, 'vertical', 'Vertical blur', 6 ],</pre>
	<p>
	  You will also note that "plug_in_" has been omitted from the
	  method call above, and that not all its parameters appear
	  to be getting passed! This is thanks to the object-oriented
	  implementation in Gimp-Perl, which when given a method name,
	  searches various prefixes for the underlying function including
	  the plug-in related ones (including <tt>script_fu_</tt>).
	<p>
	  A reference to a sub in perl may be declared in two ways.
	  Either by declaring a subroutine at a different place in the
	  source file, e.g. <tt>sub run</tt> and reference it by
	  writing <tt>\&amp;run</tt>. An alternative way is to write it
	  inline by simply writing (since with Perl's prototyping,
	  you need not supply the "sub" keyword):
	  <pre>
    podregister { ... };</pre>
	  The code will normally display a new image if it creates one,
	  and also return the new image, in accordance with the return
	  types declared in parameter 10 of the <tt>podregister</tt>
	  call described above.  This enables Gimp::Fu scripts to be
	  used noninteractively by other scripts.  More about that
	  behaviour below.
	</LI>	
      </OL>
    </LI>

<: subsection("A commented script") :>
The following Gimp::Fu script example shows the steps described in the
previous section. It registers a script that takes two values, the size
of the image and a color, and then produces an image of the requested
size with the requested color. Quite useless, but it shows the important steps
of how to register a script, how to create a new image, and how
to access some PDB functions.<p>

<: code_snippet("uni") :>

Most of these commands are directly copied out the PDB. <p>

This script shows the essential steps of producing a stand-alone
script:
<table>
  <tr><th>line(s)</th><th>Description</th>
  <tr><td>7</td><td> Registration of the extension</td></tr>
  <tr><td>9</td><td> Creating a new image.</td></tr>
  <tr><td>11</td><td> Creating one or more layers.</td></tr>
  <tr><td>12</td><td> Attaching the layer to the image. </td></tr>
  <tr><td>13-14</td><td> Do some painting operations in the layers. </td></tr>
  <tr><td>15</td><td> Display the new image</td></tr>
  <tr><td>16</td><td> Return the image to the caller</td></tr>
</table>

To test the script, save it in the directory <tt>$HOME/.gimp-2.8/plug-ins</tt>.
It must then be made executable through the command:
<pre>
     chmod +x $HOME/.gimp-2.8/plug-ins/uni
</pre>

Then start GIMP.  It is generally a good idea to test the
syntax of the script with <tt>perl -c</tt> before starting GIMP.
(A more official way to add scripts is to use the <tt>gimptool-2.0
--install-bin</tt> command).
<p>
<b>Note:</b> Due to the way GIMP works,
it is not possible to add scripts once GIMP is running. On the other hand,
it is possible to change a script which has already been registered, as
long as the parameters don't change.<p>

The script is now accessible through the menu system through the
<b>File/Create/Tutorial</b> top menu:
<center>
  <img src="uni-menu.png">
</center>
<p>
When choosing this menu entry the following screen is popped up:<p>
<center>
  <img src="uni-entry.png">
</center>
<p>
Choosing the default values results in the image:
<p>
<center>
<img src="uni-result.png">
</center>

<: section("Object oriented syntax") :>
  Gimp::Fu provides an alternative object-oriented syntax for the
  image and the drawable commands. Here is a table showing the procedural
  vs the object oriented syntax for a few commands:<p>

  <table>
    <tr><th bgcolor=#E0E0E0>procedural syntax
	<th bgcolor=#E0E0E0>object oriented syntax
    <tr><td bgcolor=#FFE0E0>gimp_image_add_layer($drw,-1);
        <td bgcolor=#FFE0E0>$img->add_layer($drw, -1);
    <tr><td bgcolor=#FFE0E0>gimp_drawable_width($drw);
        <td bgcolor=#FFE0E0>$drw->width();
  </table>
  <p>
  The substitution rule for converting a PDB turning into a method is
  as simple as erasing ``<tt>gimp_image_</tt>'' from the beginning
  of the function call and calling this method through the image object.
  Similarly for the <tt>gimp_drawable_...</tt> functions.<p>

  Note that the object oriented syntax is only syntactic sugar that
  makes the calling syntax cleaner in some cases. The error messages
  are still given in the procedural format.

<: section("Painting areas with selections") :>
In the <tt>uni</tt> script the function <tt>gimp_edit_fill</tt> was called
to fill the whole image. Looking at the info for
<tt>gimp_edit_fill</tt> in the DB browser we find the following:
<: pdb("gimp_edit_fill", "Fill selected area of drawable",
       [["drawable", "DRAWABLE", "The drawable to fill from"],
	["fill_type", "INT32", "The type of fill: GIMP_FOREGROUND_FILL (0), GIMP_BACKGROUND_FILL (1), GIMP_WHITE_FILL (2), GIMP_TRANSPARENT_FILL (3), GIMP_PATTERN_FILL (4)"]
],
       "",
       "This procedure fills the specified drawable with the fill mode. If the fill mode is foreground, the current foreground color is used. If the fill mode is background, the current background color is used. Other fill modes should not be used. This procedure only affects regions within a selection if there is a selection active."

) :>

<p>
Thus, if a selection is active when <tt>gimp_edit_fill</tt>
is called only the selection is painted. Note also that you should
erase the "GIMP_" part of the constant names.

<p>There are lots of ways of
choosing a selection as can be seen when searching for a ``select''
in the PDB. The example below uses <tt>gimp_rect_select</tt>,
whose entry in the PDB looks as follows:
<: pdb("gimp_rect_select",
       "Create a rectangular selection over the specified image",
       [ ["image", "IMAGE", "The image"],
         ["x", "FLOAT", "x coordinate of upper-left corner of rectangle"],
         ["y", "FLOAT", "y coordinate of upper-left corner of rectangle"],
         ["width", "FLOAT", "the width of the rectangle: width \> 0"],
         ["height", "FLOAT", "the height of the rectangle: width \> 0"],
         ["operation", "INT32", "the selection operation: {GIMP_CHANNEL_OP_ADD (0), GIMP_CHANNEL_OP_SUB"
          . "(1), GIMP_CHANNEL_OP_REPLACE (2), GIMP_CHANNEL_OP_INTERSECT (3) }"],
         ["feather", "INT32", "feather option for selections"],
         ["feather_radius", "FLOAT", "radius for feather operation"] 
],
       "",
       "This tool creates a rectangular selection over the specified image. The rectangular region can be either added to, subtracted from, or replace the contents of the previous selection mask. If the feather option is enabled, the resulting selection is blurred before combining. The blur is a gaussian blur with the specified feather radius."       
) :>

A simple use of this function which selects a rectangle in the middle
of an image and paints that rectangle with a user defined color.
This example also introduces a couple of new features we haven't seen
before:
<UL>
  <LI> The script is associated with an image since its menu
       path starts with "&lt;Image&gt;/...". Note that as a result of this
       the callback sub in line 13 receives two additional
       parameters, the active image and the seleced drawable.</LI>
  <LI> The use of a subroutine without a name as a parameter to
       <tt>podregister</tt></LI>
  
  <LI> The use of the PDB functions <tt>gimp_undo_push_group_start</tt>
       and <tt>gimp_undo_push_group_end</tt>. These functions declare
       an undo group. When an undo is done on the image, instead of
       having the individual operators undo, all the actions between
       the undo start and the undo group calls will be undone at once.</LI>
  
  <LI> The return type of the podregister function defines what new
       images should be displayed by gimp. In this case we don't
       want to display any new images and therefore return an empty array.
  </LI>
</UL>

<: code_snippet("paint-select") :>

The result when run on our previous image:
<center>
<img src="paint-select.png">
</center>

<: subsection("Complex selections") :>
  Besides rectangular selections elliptical selections may also be
  created through the PDB functions <tt>gimp_ellipse_select()</tt>
  and <tt>gimp_free_select()</tt> which allows the selection of
  ellipses and polygons.
  <p>
  More complex selections may be created through the channel mechanism.
  The PDB <tt>gimp_channel_new()</tt> creates a new channel. The channel
  is a drawable that may be painted into, just like any other drawable,
  but with the difference that it is always a grey level image. Once
  the channel is finished, the channel may be loaded into the selection 
  through the PDB function <tt>gimp_selection_load()</tt>.
  <p>
    Search for ``select'' in the DB Browser to see a list of all the
    selection related functions.

<: subsection("Loops") :>
In perl it is trivial to write loops that together with the various
selecton tools gives powerful creative possibilities. Here is
an example that mixes colors in circles. There is nothing really new
here, but it shows the power of the what we have described above.
<: code_snippet("circles") :>
The result:
<center>
<img src="circles.png">
</center>

<: section("Creating text") :>

<: subsection("Hello World - writing text in an image") :>

To create text the PDB function <tt>gimp_text_fontname()</tt> may be
used. In this function the font is specified in the X11 font conventions.

<p> Here is an example of a script that creates an image containing
"Hello world".
<: code_snippet("hello-world1") :>

The result:
<center>
<img src="hello-world1.png">
</center>
The script makes uses a simple regular expression to extract the
font size from the font name. This is necessary as the authors
of <tt>gimp_text_fontname</tt> decided that the font size within the fontname
is ignored.
<p>
One thing to note in this script is that the text that is created on
line 24 is a <i>floating layer</i>, than needs to be anchored to its
parent layer. This is done in line 27 through the call to
<tt>gimp_floating_sel_anchor()</tt>.<p>

This script suffers from the problem that the image size is unrelated
to the text size. This is taken care of in the following more
complex example which shows the basic steps for a logo generating
script. 
<UL>
  <LI> Creation of an image arbitrary size </LI>
  <LI> Creation of a background drawable of an arbitrary size </LI>
  <LI> Creation of text layer which exactly fits the text with the command
       <tt>gimp_text_fontname()</tt>.
  <LI> Resizing the image and the background to the size of the text layer. </LI>
</UL>
The result is an image composed of two layers; a transparent text layer
on top of a uniform background.
<p>

<: code_snippet("basic-logo") :>
  <p>
  Note the special syntax of <tt>gimp_image_text_fontname()</tt>
  in line 24 in <tt>basic-logo</tt> with an image specified for a
  first parameter, and the drawable = -1. This is in contradiction
  to the rule above that the image should not be specified for 
  PDB functions that take both an image and a drawable as the first
  two parameters. But since
  the drawable=-1, which has no image related to it, an image explicitely
  be provided. The special case drawable=-1 means that instead of
  creating a floating layer, a new image layer will be created.

  <p>
    The result shown in the following dialog and the resulting image:
    <p>
<center>
<img src="basic-logo-dialog.png"><img src="tpix.gif" width=20>
<img src="basic-logo.png">
</center>
    <p>

<: section("Floating selections") :>
  When a region has been selected through one of the selection routines
  the area outlined by the selection may be copied to the cut-buffer
  through the <tt>gimp_edit_copy</tt> command. The cut-buffer may
  subsequently be pasted into a different layer through the
  <tt>gimp_edit_paste</tt> command. When a layer is pasted it becomes
  a floating selection. This floating selection may be moved to
  its required position by the command <tt>gimp_layer_set_offsets</tt>,
  and finally it is pasted by the <tt>gimp_floating_sel_anchor</tt>
  command. Another way of
  determining the position of a pasted layer is to create a selection in
  the target image before the cut-buffer is pasted. <p>

  This is illustrated in the following program, which works on one image
  and takes as a parameter an another image, which it concatinates to
  the right of the first image. The lines 28-38 shows how the second
  image is copied and glued into the first image.<p>
  <: code_snippet("horiz-cat") :>

<: section("The Perl Server and stand-alone scripts") :>
  So far the scripts have all been started from the menu structure
  within menu. But there is another possibility and that is to run
  the scripts from the command line, as a normal perl program. When
  run this way the script tries to connect to the Perl-Server, and
  if it fails it will launch gimp on its own. If you plan to run
  several scripts this way, it is obviously much faster to run the
  Perl-Server since launching gimp takes quite a bit of time. The
  perl-server may be started from the Xtns menu.
  <p>

  When a perl-fu script is run from the command line, the
  result is the same as when it is run through the menus, except
  of the fact that it may be run with the <tt>--output</tt> parameter
  in case it will save the result to a file instead of displaying
  it within gimp. This is great for batch creation of logos, etc. <p>

  The filename for the <tt>--output</tt> has some special magic that
  allows to set some special image saving parameters, like interlace,
  quality factor, etc. See the Gimp::Fu man page for details.</t>

  Note that the normal rules about image and file types are still valid,
  thus e.g. in order to save an image as a gif file, it must be converted
  from RGB to an indexed script. Currently this functionality must be
  included in each script, but it is possible that a future version
  of Gimp::Fu, includes this conversion as an option. <P>
 
  Here are two invocations of the scripts declared above, but with output
  written to a jpg file and a png file. As we said above, we can't save
  them as gif as the scripts do not index the images.<p>

  <: code_snippet("perl-gimp-from-shell") :>

  Another importent use of this interface is that it enables running
  the perl debugger on the perl-fu scripts.<p>
  
  <b>Note:</b> The image is saved to the directory
  where gimp was started from and not to the directory in which the
  scripts were invoked. Thus it is recommended to use a complete path.

<: subsection("A shell for gimp-perl") :>
  When using the perl-server it is not necessary to use <tt>Gimp::Fu</tt>
  and the <tt>podregister</tt> function. Instead a sub named <tt>on_net</tt>
  may be declared, which takes as a parameter a reference to a sub
  routine that is called when gimp starts.
  <p>
  For a simple but powerful example of the use of the Gimp without
  Fu, here is a an interactive perl gimp shell that may be run from
  the command line:
  <p>
  <: code_snippet("pg-shell") :>
    <p>
  Here is an example of an interactive session with this shell:
  <: code_snippet("interact") :>

<: section("End notes") :>
  This tutorial has covered only a small part of the possibilities
  available to a script writer. In particular the following issues
  available to Gimp::Perl scripts have not been covered:

  <UL>
    <LI> The possibility of writing customized Gtk interfaces. </LI>
    
    <LI> Writing fullfledged plug-ins that manipulate the tile data
         through the Perl Data Language (PDL) module.</LI>
    <LI> Using Perl::Gimp in a CGI environment. </LI>
    <LI> How to fill with gradients in a plugin </LI>
    <LI> How to do "free selections". </LI>
  </UL>

<: section("Links and references") :>
  <UL>
    <LI> <A HREF="scheme-tut.html">The scheme tutorial this tutorial is based on</A> </LI>
    
    <LI> <a href="http://www.gimp.org">The Gimp home page</a> </LI>
    
    <LI> <A HREF="http://registry.gimp.org/">Gimp Registry with Perl plug-ins</A> </LI>
  </UL>

<hr>
<address>Please send your comments to <a href="mailto:dov.grobgeld@gmail.com">dov.grobgeld@gmail.com</a></address>
</box>
</body> </html>
